language: node_js
node_js:
  - "10.13"
compiler:
  - gcc
  - clang
env:
  - CXX=g++-4.8
cache:
  directories:
    - "node_modules"
before_install:
  - npm install -g node-gyp
  - npm install -g yarn
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
install:
  - yarn install
script:
  - yarn test:unit
  - yarn run build
