language: node_js
services:
  - docker
node_js:
  - "10.16"
compiler:
  - gcc
  - clang
env:
  - CXX=g++-4.8
cache:
  directories:
    - "node_modules"
before_install:
  - npm install -g node-gyp
  - npm install -g yarn
  - pip install awscli --user
  - pip install boto3 --user
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
install:
  - yarn install
script:
  - yarn test:unit
  - yarn run build
deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
