language: node_js
services:
  - docker
node_js:
  - "10.16"
compiler:
  - gcc
  - clang
env:
  - CXX=g++-4.8
cache:
  directories:
    - "node_modules"
before_install:
  - npm install -g node-gyp
  - npm install -g yarn
  - pip install awscli --user
  - pip install boto3 --user
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
install:
  - yarn install
script:
  - yarn test:unit
jobs:
  include:
    - stage: build mainnet
      script: run build:mainnet
      if: branch = mainnet
    - stage: build rinkeby
      script: run build:rinkeby
      if: branch = rinkeby
    - stage: build skynet
      script: run build:skynet
      if: branch = skynet
    - stage: build master
      script: run build:master
      if: branch = master
deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh
    on:
      branch: skynet
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh
    on:
      branch: rinkeby
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh
    on:
      branch: mainnet
