language: node_js
env:
  - CXX=g++-5
node_js:
  - stable
cache:
  directories:
    - "node_modules"
before_install:
  - npm install -g node-gyp
  - npm install -g yarn
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
install:
  - yarn install
script:
  - yarn test:unit
  - yarn run build
