language: node_js
services:
  - docker
node_js:
  - "10.16"
compiler:
  - gcc
  - clang
env:
  - CXX=g++-4.8
cache:
  directories:
    - "node_modules"
before_install:
  - npm install -g node-gyp
  - npm install -g yarn
  - pip install awscli --user
  - pip install boto3 --user
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
install:
  - yarn install
script:
  - yarn test:unit
  - if [ "$TRAVIS_BRANCH" = "mainnet" ]; then yarn run build:mainnet; fi
  - if [ "$TRAVIS_BRANCH" = "rinkeby" ]; then yarn run build:rinkeby; fi
  - if [ "$TRAVIS_BRANCH" = "skynet" ]; then yarn run build:skynet; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then yarn run build:master; fi
deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy_with_auth.sh
    on:
      branch: mainnet
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh
    on:
      branch: rinkeby
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh
    on:
      branch: skynet
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh
    on:
      branch: master
