<template>
  <div>
    <h4 id="-effective-as-of-november-14-2019-"><strong>Effective as of November 14, 2019.</strong></h4>
    <br />
    <p>PLEASE READ THIS BETA EVALUATION TERMS OF SERVICE AGREEMENT (THE <strong>“AGREEMENT”</strong>) CAREFULLY.  BY ACCESSING OR USING THE SERVICES AND RESOURCES AVAILABLE OR ENABLED VIA THE COMPUTABLE WEBSITE  (THE <strong>“WEBSITE”</strong>), CLICKING TO ACCEPT OR AGREE TO THIS AGREEMENT WHERE THAT OPTION IS MADE AVAILABLE TO YOU, AND/OR BROWSING THE WEBSITE, YOU REPRESENT THAT (1) YOU HAVE READ, UNDERSTAND, AND AGREE TO BE BOUND BY THIS AGREEMENT; (2) YOU ARE OF LEGAL AGE TO FORM A BINDING CONTRACT WITH COMPUTABLE, LLC (<strong>“COMPANY”</strong>); AND (3) YOU HAVE THE AUTHORITY TO ENTER INTO THE AGREEMENT PERSONALLY OR ON BEHALF OF THE LEGAL ENTITY YOU HAVE NAMED AS THE USER, AND TO BIND THAT LEGAL ENTITY TO THIS AGREEMENT.  THE TERM <strong>“USER”</strong> OR <strong>“YOU”</strong> REFERS TO THE INDIVIDUAL OR LEGAL ENTITY, AS APPLICABLE, IDENTIFIED AS THE USER WHEN YOU REGISTERED ON THE WEBSITE.  IF YOU DO NOT AGREE TO BE BOUND BY THIS AGREEMENT, YOU MAY NOT ACCESS OR USE THE SERVICES.</p>
    <br />
    <p>PLEASE NOTE THAT THIS AGREEMENT IS SUBJECT TO CHANGE BY COMPANY IN ITS SOLE DISCRETION AT ANY TIME.  When changes are made, Company will make a new copy of the Agreement available at the Website.  Company will also update the “Last Updated” date at the top of the Agreement. If we make any material changes, and you have provided us with your e-mail address, we will also send an e-mail to you at the last e-mail address you provided to us.  We may require you to provide consent to the updated Agreement in a specified manner before further use of the Service is permitted.  If you do not agree to any change(s) after receiving a notice of such change(s), you shall stop using the Service.  Otherwise, your continued use of the Service constitutes acceptance of such change(s).  PLEASE REGULARLY CHECK THE WEBSITE TO VIEW THE THEN-CURRENT AGREEMENT.</p>
    <p><strong>PLEASE BE AWARE THAT SECTION 3.6 OF THIS AGREEMENT PROHIBITS YOU FROM POSTING OR SHARING PERSONAL INFORMATION THROUGH THE SERVICE, AND SECTION 4.7 DEFINES THE TERM, “PERSONAL INFORMATION.”</strong></p>
    <p><strong>SECTION 2.5 OF THIS AGREEMENT PROHIBITS YOU FROM USING THE PLATFORM IF YOU ARE A RESIDENT OF ANY COUNTRY OTHER THAN THE UNITED STATES.</strong></p>
    <br/>
    <h3 id="-1-service-"><strong>1. SERVICE.</strong></h3>
    <p><strong>1.1</strong>    You wish to obtain, and Company has agreed to provide you with, access to a beta, untested version of the Service (as defined below) solely for the purposes of evaluating the Services in accordance with the terms of this Agreement.
    <strong>1.2</strong>    Company has developed a software platform (<strong>“Platform”</strong>) by which (i) registered Users (<strong>“Content Providers”</strong>) are able to upload content, data, or information (<strong>“Content”</strong>) to the Platform (ii) Content Providers can share their Content with registered Users that purchase access to Content (<strong>“Content Purchasers”</strong>); (iii) Content Purchasers receive access to Content by making payments through the Platform; and (iv) Content Providers receive Market Tokens in return for sharing access of their Content with Content Purchasers ((i) through (iv) collectively, the <strong>“Service”</strong>).
    <strong>1.3</strong>    All the transactions on the Platform are executed by virtue of the smart contracts developed by Company (<strong>“Smart Contracts”</strong>) and all payments made on the Platform are made in Ethereum (ETH). <strong>“Market Tokens”</strong> mean the ERC20 tokens that Content Providers receive on the Platform in return for their upload and sale of Content with Content Purchasers.
    <strong>1.4</strong>    Users may only participate in transactions on the Platform by linking their digital wallets on MetaMask (<a href="https://metamask.io/">https://metamask.io/</a>). MetaMask is an electronic wallet, which allows Users to purchase, store, and engage in transactions using Ethereum cryptocurrency.  Before uploading any Content for sharing or making an offer to purchase access to Content from a Content Provider, the User will be prompted to download the MetaMask extension, and connect and unlock the User’s digital wallets with MetaMask. Once a user submits an order to sell or purchase access to Content, this order is passed on to MetaMask and MetaMask completes the transaction on the User’s behalf.
    <strong>1.5</strong>    Further details regarding the Service, Market Tokens <strong>[and our registration process]</strong> are set forth in the <strong>FAQ page available here: [insert url]</strong>, the terms of which are incorporated in this Agreement by reference.
    <br/></p>
    <br/>
    <h3 id="-2-user-responsibility-"><strong>2. USER RESPONSIBILITY</strong></h3>
    <p><strong>2.1</strong>    You represent that you are (a) at least thirteen (13) years old; (b) of legal age to form a binding contract; and (c) not a person barred from using Website or Service under the laws of the United States, your place of residence or any other applicable jurisdiction.  You are responsible for all activities that occur under your Ethereum account.  You agree that you shall monitor your Ethereum accounts to restrict use by minors, and you will accept full responsibility for any unauthorized use of your Ethereum account, Website or Service by minors.  You may not share your Ethereum account or password with anyone, and you agree to (y) notify Company immediately of any unauthorized use of your password or any other breach of security; and (z) exit from your Ethereum account at the end of each session.  If Company requests any information from you to verify your identity and you provide any information that is untrue, inaccurate, not current or incomplete, or Company has reasonable grounds to suspect that any information you provide is untrue, inaccurate, not current or incomplete, Company has the right to suspend or terminate your current or future use of Website or Service (or any portion thereof).  You agree not to create an Ethereum account using a false identity or information, or on behalf of someone other than yourself.    You agree not to use Website or Service if you have been previously banned from any of Website or Service.</p>
    <p><strong>2.2    Necessary Equipment and Software.</strong>  You must provide all equipment and software necessary to connect to Website and Service, including but not limited to, a mobile device that is suitable to connect with and use Website and Service, in cases where the Services offer a mobile component.  You are solely responsible for any fees, including Internet connection or mobile fees, that you incur when accessing Website or Service.  </p>
    <p><strong>2.3    Only for US Users.</strong> Users that are not residents of the United States are NOT PERMITTED to register an Account on the Website or participate or use the Services. Website and Services may be accessed from countries around the world and may contain references to Services that are not available in your country.  These references do not imply that Company intends to announce such Services in your country.  Services and Website are controlled and offered by Company from its facilities in the United States of America. Company makes no representations that Website or Service are appropriate or available for use in other locations.  Those who access or use Website and Services from other countries do so at their own volition and are responsible for compliance with local law.</p>
    <br/>
    <h3 id="-3-license-restrictions-obligations-"><strong>3.    LICENSE; RESTRICTIONS; OBLIGATIONS.</strong></h3>
    <p><strong>3.1    Beta Use.</strong>  You understand that the version of the Service provided pursuant to this Agreement is a prerelease version that has not yet completed Company’s quality assurance testing.  You agree to use good faith efforts to test, use and evaluate the Service and to promptly report to Company any errors, problems, defects or suggestions for changes and improvements to the Service (collectively, <strong>“Feedback”</strong>) during an evaluation period, which shall begin on the date that Company notifies you that the Service is available to you for use and shall terminate on the earlier of (a) the date of termination of the evaluation period, as set forth in a Company notice posted on the Website or (b) the date on which Company launches a commercial version of the Service (the <strong>“Evaluation Term”</strong>).  You represent that you have all rights necessary to submit the Feedback.  You hereby grant to Company a fully paid, royalty-free, perpetual, irrevocable, worldwide, non-exclusive, and fully sublicensable right and license to use, reproduce, perform, display, distribute, adapt, modify, re-format, create derivative works of, and otherwise commercially or non-commercially exploit in any manner, any and all Feedback, and to sublicense the foregoing rights, in connection with the operation of the Website, Service, and/or Company’s business.  Providing the Service to you does not constitute a sale or an announcement that a commercial version of the Service, or that any other service of a similar design and/or functionality, will be available from Company.</p>
    <p><strong>3.1    Software.</strong>  Use of, or access to, any software and associated documentation that is made available via the Service (<strong>“Software”</strong>) is governed by the terms of the license agreement that accompanies or is included with the Software.  You shall not use, download or install any Software that is accompanied by or includes a license agreement unless you agree to the terms of such license agreement.  If no license accompanies use of the Software, your use of the Software will be governed by this Agreement.  Subject to your compliance with this Agreement, Company grants you a non-assignable, non-transferable, non-sublicensable, revocable non-exclusive license to use the Software for the sole purpose of enabling you to use the Service in the manner permitted by the Agreement during the evaluation period.  Some Software may be offered under an open source license that we will make available to you.  There may be provisions in the open source license that expressly override these terms.  At no time will Company provide you with any tangible copy of the Software.  </p>
    <p><strong>3.2    Certain Restrictions.</strong>  Except as permitted in this Agreement, the rights granted to you in this Agreement are subject to the following restrictions:</p>
    <p><strong>(a)</strong>    You shall not cause the Website or Service in any way to be disassembled, decompiled, reverse engineered, or otherwise attempt to derive the source code or algorithms in the Website or Service, except to the extent permitted by applicable law (and provided that you must first request such information from Company and Company may either provide such information or impose reasonable conditions, including a fee, on such use to ensure that Company’s intellectual property rights are protected), or workaround any technical information in the Service, nor shall any attempt to do any of the foregoing be undertaken or permitted;</p>
    <p><strong>(b)</strong>    You shall not make the Website or Service available for access or use by any person or entity other than Customer’s employees;</p>
    <p><strong>(c)</strong>    You shall not rent, lease, loan or sell access to the Website or Service to any third party or provide it as a service bureau;</p>
    <p><strong>(d)</strong>    You shall not interfere with or disrupt the Service;</p>
    <p><strong>(e)</strong>    You shall not copy or otherwise reproduce, translate, port, modify or make derivative works of the Website or Service; and</p>
    <p><strong>(f)</strong>    You shall not publish any performance or benchmark tests or analysis related to the Website or Service.</p>
    <p><strong>3.3    Third Party Materials.</strong>  As a part of the Service, you may have access materials that are hosted by another party.  You agree that it is not possible for Company to monitor such materials and that your access to these materials is at your risk.</p>
    <br/>
    <h3 id="-4-ownership-"><strong>4.    OWNERSHIP.</strong></h3>
    <p><strong>4.1    Website or Service.</strong>  You agree that Company and its suppliers (<strong>“Suppliers”</strong>) own all rights, title and interest in the Website and Service.  You will not remove, alter or obscure any copyright, trademark, service mark or other proprietary rights notices incorporated in or accompanying the Website and Service.</p>
    <p><strong>4.2    Trademarks.</strong>  Company’s name and other related graphics, logos, service marks and trade names used on or in connection with the Website or Service are the trademarks of Company and may not be used without permission in connection with any third-party product or services. Other trademarks, service marks and trade names that may appear on or in the Website or Service are the property of their respective owners.</p>
    <p><strong>4.3    Ownership of Content; License Grant.</strong> Company does not claim ownership of your Content. However, when you as a user post or publish your Content on or in the Platform, you represent that you own and/or have a royalty-free, perpetual, irrevocable, worldwide, non-exclusive right (including any moral rights) and license to use, license, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, derive revenue or other remuneration from, and communicate to the public, perform and display your Content (in whole or in part) worldwide and/or to incorporate it in other works in any form, media or technology now known or later developed, for the full term of any worldwide intellectual property right that may exist in your Content.  You acknowledge and agree that you are granting each Content Purchaser with which you share or sell your Content, a license to use that Content under the Creative Commons Attribution 4.0 International License, which can be accessed at <a href="https://creativecommons.org/licenses/by/4.0/">https://creativecommons.org/licenses/by/4.0/</a>.</p>
    <p><strong>4.4    Other Content.</strong>  Except as provided herein, you agree that you have no right or title in or to any content that appears on or in the Website or Service.</p>
    <p><strong>4.5    Procedure for Making Claims of Copyright Infringement.</strong> It is our policy to terminate account privileges of any user who repeatedly infringes copyright upon prompt notification to Company by the copyright owner or the copyright owner’s legal agent.  Without limiting the foregoing, if you believe that your work has been copied and posted on the Platform in a way that constitutes copyright infringement, please provide our Copyright Agent with the following information: (1) an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest; (2) a description of the copyrighted work that you claim has been infringed; (3) a description of the location on Site of the material that you claim is infringing; (4) your address, telephone number and e-mail address; (5) a written statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent or the law; and (6) a statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner’s behalf.  Contact information for Company’ Copyright Agent for notice of claims of copyright infringement is as follows: Copyright Operations, Computable LLC, 832 Sansome St First Floor, San Francisco,  CA  94111, Phone: 4156175959, Email: <a href="mailto:copyright@computable.io">copyright@computable.io</a>.</p>
    <p><strong>4.6    Acceptable Use Policy.</strong> By providing Content via the Service, you represent and warrant that Content, and the use of your Content as contemplated by this Agreement, does not and will not: (a) infringe, violate, or misappropriate any third party right, including any copyright, trademark, patent, trade secret, moral right, privacy right, right of publicity, or any other intellectual property or proprietary right; (b) slander, defame, libel, or invade the right of privacy, publicity or other property rights of any other person; (c) violate, or cause Company to violate, any law or regulation; (c) include any child pornography; or (e) include any Personal Information (as defined in Section 4.7) about you or a third party. You agree to comply with Company’s Acceptable Use Policy set forth in <a href="https://www.computable.io/community-guidelines">www.computable.io/community-guidelines</a> and acknowledge that Company may in its discretion terminate account privileges of any user who violates the Acceptable Use Policy.</p>
    <p><strong>4.7    Definition of Personal Information.</strong> “Personal information” means information that identifies, relates to, describes, is capable of being associated with, or could reasonably be linked, directly or indirectly, with a particular consumer or household. Personal information includes, but is not limited to, the following if it identifies, relates to, describes, is capable of being associated with, or could be reasonably linked, directly or indirectly, with a particular consumer or household:</p>
    <p><strong>(a)</strong>    Identifiers such as a real name, alias, postal address, unique personal identifier, online identifier, Internet Protocol address, email address, account name, social security number, driver’s license number, passport number, or other similar identifiers.</p>
    <p><strong>(b)</strong>    Any categories of personal information described in subdivision (e) of Section 1798.80.</p>
    <p><strong>(c)</strong>    Characteristics of protected classifications under California or federal law.</p>
    <p><strong>(d)</strong>    Commercial information, including records of personal property, products or services purchased, obtained, or considered, or other purchasing or consuming histories or tendencies.</p>
    <p><strong>(e)</strong>    Biometric information.</p>
    <p><strong>(f)</strong>    Internet or other electronic network activity information, including, but not limited to, browsing history, search history, and information regarding a consumer’s interaction with an Internet Web site, application, or advertisement.</p>
    <p><strong>(g)</strong>    Geolocation data.</p>
    <p><strong>(h)</strong>    Audio, electronic, visual, thermal, olfactory, or similar information.</p>
    <p><strong>(i)</strong>    Professional or employment-related information.</p>
    <p><strong>(j)</strong>    Education information, defined as information that is not publicly available personally identifiable information as defined in the Family Educational Rights and Privacy Act (20 U.S.C. section 1232g, 34 C.F.R. Part 99).</p>
    <p><strong>(k)</strong>    Inferences drawn from any of the information identified in this subdivision to create a profile about a consumer reflecting the consumer’s preferences, characteristics, psychological trends, predispositions, behavior, attitudes, intelligence, abilities, and aptitudes.</p>
    <p>“Personal information” does not include publicly available information. For these purposes, “publicly available” means information that is lawfully made available from federal, state, or local government records, if any conditions associated with such information. “Publicly available” does not mean biometric information collected by a business about a consumer without the consumer’s knowledge. Information is not “publicly available” if that data is used for a purpose that is not compatible with the purpose for which the data is maintained and made available in the government records or for which it is publicly maintained. “Publicly available” does not include consumer information that is deidentified or aggregate consumer information. We handle, store and disclose Personal Information in accordance with our Privacy Policy available here: <a href="https://www.computable.io/privacy-policy">www.computable.io/privacy-policy</a>.</p>
    <br/>
    <h3 id="-5-disclaimer-of-warranties-"><strong>5.    DISCLAIMER OF WARRANTIES.</strong></h3>
    <p>YOU ACKNOWLEDGE AND AGREE THAT THE VERSION OF THE SERVICE THAT IS PROVIDED TO YOU PURSUANT TO THIS AGREEMENT IS A PRERELEASE, UNTESTED VERSION AND IS PROVIDED “AS IS” AND “AS AVAILABLE”  AND THAT COMPANY AND ITS SUPPLIERS HAVE MADE NO REPRESENTATIONS, WARRANTIES OR CONDITIONS OF ANY KIND, ORAL, STATUTORY, EXPRESS, IMPLIED, BY COURSE DEALING OR OTHERWISE.  COMPANY AND ITS SUPPLIERS SPECIFICALLY DISCLAIM ANY WARRANTY WITH REGARD TO TITLE, MERCHANTABILITY, NON-INFRINGEMENT OR FITNESS FOR ANY PARTICULAR PURPOSE.  WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, YOU ACKNOWLEDGE AND AGREE THAT COMPANY DOES NOT WARRANT THAT THE SERVICE WILL BE ERROR-FREE OR WILL OPERATE WITHOUT INTERRUPTION, AND COMPANY GRANTS NO WARRANTY REGARDING ITS USE OR THE RESULTS THEREFROM.</p>
    <p>YOU ACKNOWLEDGE AND AGREE THAT COMPANY MAKES NO REPRESENTATIONS, WARRANTIES OR CONDITIONS OF ANY KIND, ORAL, STATUTORY, EXPRESS, IMPLIED, BY COURSE OF DEALING OR OTHERWISE, WITH REGARD TO TITLE, MERCHANTABILITY, NON-INFRINGEMENT OR FITNESS FOR ANY PARTICULAR PURPOSE RELATED TO THE CONTENT THAT YOU PURCHASE THROUGH THE SERVICE AND THAT YOUR SOLE REMEDY, IF ANY, FOR SUCH CONTENT IS FROM THE CONTENT PROVIDER, NOT COMPANY.  YOU ACKNOWLEDGE AND AGREE THAT CONTENT PROVIDERS ARE SOLELY LIABLE FOR ANY CONSEQUENCES, HARM OR LOSS RESULTING FROM SHARING OF CONTENT WITH CONTENT PURCHASERS OR THIRD PARTIES ON THE PLATFORM. COMPANY DOES NOT GUARANTEE THAT ANY CONTENT PURCHASERS WILL PURCHASE ACCESS TO ANY CONTENT. COMPANY DOES NOT GUARANTEE THAT ANY CONTENT UPLOADED, POSTED FOR PURCHASE OR PURCHASED VIA THE PLATFORM WILL BE AS ADVERTISED OR DESCRIBED BY CONTENT PROVIDER.</p>
    <p>YOU ACKNOWLEDGE AND AGREE THAT COMPANY MAKES NO REPRESENTATIONS, WARRANTIES OR CONDITIONS OF ANY KIND, ORAL, STATUTORY, EXPRESS, IMPLIED, BY COURSE OF DEALING OR OTHERWISE, REGARDING THE HOSTING OF YOUR CONTENT AND THAT COMPANY SHALL HAVE NO LIABILITY IN THE EVENT THAT SUCH CONTENT IS DAMAGED OR DESTROYED.</p>
    <p>THE PARTIES ACKNOWLEDGE THAT THE REGULATORY REGIME GOVERNING BLOCKCHAIN TECHNOLOGIES, CRYPTOCURRENCIES, AND TOKENS IS UNCERTAIN, AND NEW REGULATIONS OR POLICIES MAY MATERIALLY ADVERSELY AFFECT THE SERVICE AND/OR THE UTILITY/VALUE OF MARKET TOKENS.</p>
    <p>THE SERVICE WILL RELY ON THIRD-PARTY PLATFORMS SUCH AS METAMASK TO PERFORM THE TRANSACTIONS RELATED TO THE SHARING AND PURCHASING OF CONTENT. IF COMPANY IS UNABLE TO MAINTAIN A GOOD RELATIONSHIP WITH SUCH PLATFORM PROVIDERS; IF THE TERMS AND CONDITIONS OR PRICING OF SUCH PLATFORM PROVIDERS CHANGE; IF COMPANY VIOLATES OR CANNOT COMPLY WITH THE TERMS AND CONDITIONS OF SUCH PLATFORMS; OR IF ANY OF SUCH PLATFORMS LOSES MARKET SHARE OR FALLS OUT OF FAVOR OR IS UNAVAILABLE FOR A PROLONGED PERIOD OF TIME, ACCESS TO AND USE OF THE SERVICE WILL SUFFER, AND YOU AGREE THAT COMPANY SHALL NOT BE HELD LIABLE FOR ANY SUCH ADVERSE EFFECT.</p>
    <p>THE PARTIES ACKNOWLEDGE THAT THERE ARE RISKS ASSOCIATED WITH USING AN INTERNET BASED CURRENCY, INCLUDING BUT NOT LIMITED TO, THE RISK OF HARDWARE, SOFTWARE AND INTERNET CONNECTIONS, THE RISK OF MALICIOUS SOFTWARE INTRODUCTION, AND THE RISK THAT THIRD PARTIES MAY OBTAIN UNAUTHORIZED ACCESS TO CONTENT STORED ON THE COMPANY’S SERVERS. YOU ACCEPT AND ACKNOWLEDGE THAT COMPANY WILL NOT BE RESPONSIBLE FOR ANY COMMUNICATION FAILURES, DISRUPTIONS, ERRORS, DISTORTIONS OR DELAYS YOU MAY EXPERIENCE WHEN USING THE WEBISTE, SERVICE, MARKET TOKENS OR SHARING OR PURCHASING CONTENT, HOWEVER CAUSED. COMPANY SHALL NOT BE HELD LIABLE FOR ANY FAILURE, ERROR, COMPROMISE, BREACH OR UNAUTHORIZED ACCESS OF THE SMART CONTRACTS OR METAMASK WALLETS.</p>
    <br/>
    <h3 id="-6-limitation-of-liability-"><strong>6.    LIMITATION OF LIABILITY.</strong></h3>
    <p><strong>6.1    Type of Damages.</strong>  NEITHER PARTY SHALL BE LIABLE TO THE OTHER PARTY FOR ANY INDIRECT, SPECIAL, CONSEQUENTIAL, RELIANCE, OR PUNITIVE DAMAGES, OR FOR ANY LOSS OF PROFITS, DATA, REVENUE, OR FOR DAMAGE TO REPUTATION OR GOOD WILL, HOWEVER ARISING UNDER THIS AGREEMENT OR IN CONNECTION WITH THE WEBSITE, , SERVICE, OR CONTENT, WHETHER UNDER CONTRACT, TORT OR OTHERWISE, REGARDLESS OF WHETHER FORESEEABLE OR NOT AND REGARDLESS OF WHETHER SUCH PARTY HAS BEEN ADVISED OF THE POSSIBILITY THAT SUCH DAMAGES MAY ARISE, OCCUR OR RESULT.</p>
    <p><strong>6.2    Amount of Damages.</strong>  IN NO CASE SHALL COMPANY’S AGGREGATE CUMULATIVE LIABILITY TO YOU FOR ANY CLAIM EXCEED THE GREATER OF THE AMOUNTS PAID BY YOU TO COMPANY PURSUANT TO THIS AGREEMENT AND $1000.  THE EXISTENCE OF ONE OR MORE CLAIMS UNDER THIS AGREEMENT WILL NOT INCREASE COMPANY’S LIABILITY.  </p>
    <p><strong>6.3    Basis of Bargain.</strong>  These limitations of liability will apply notwithstanding any failure of essential purpose of any limited remedy.  The parties acknowledge that the prices have been set and the Agreement entered into in reliance upon these limitations of liability, and that all such limitations form an essential basis of the bargain between the parties.</p>
    <br/>
    <h3 id="-7-term-and-termination-"><strong>7.    TERM AND TERMINATION.</strong></h3>
    <p><strong>7.1    Term.</strong>  The Term of this Agreement commences on the Effective Date and terminates on expiration of the Evaluation Term, unless terminated earlier in accordance with this Agreement.</p>
    <p><strong>7.2    Termination of Service for Cause.</strong>  If either party materially breaches any provision of the Agreement, the non-breaching party has the right to terminate the Agreement if the breaching party has not cured the breach within thirty (30) days after notice thereof.</p>
    <p><strong>7.3    Effect of Termination.</strong>  Termination of the Agreement may include, any or all of the following, at Company’s sole discretion:  removal of your Content from the Service, removal of your access to the Service, and barring of further use of the Service and any Software.  All provisions of the Agreement which by their nature should survive, shall survive termination of the Agreement, including without limitation, ownership provisions, warranty disclaimers, and limitations of liability.</p>
    <br/>
    <h3 id="-8-miscellaneous-"><strong>8.    MISCELLANEOUS.</strong></h3>
    <p><strong>8.1    Force Majeure.</strong>  Any delay in the performance of any duties or obligations of either party (except the payment of money owed) will not be considered a breach of this Agreement if such delay is caused by a labor dispute, shortage of materials, fire, earthquake, flood, or any other event beyond the control of such party, provided that such party uses reasonable efforts, under the circumstances, to notify the other party of the cause of such delay and to resume performance as soon as possible.</p>
    <p><strong>8.2    Governing Law.</strong>  This Agreement and any action related thereto will be governed and interpreted by and under the laws of the State of California, without giving effect to any conflicts of laws principles that require the application of the law of a different jurisdiction. You hereby expressly consent to the personal jurisdiction and venue in the state and federal courts for the county in which Company’s principal place of business is located for any lawsuit filed there against you by Company arising from or related to this Agreement.  The United Nations Convention on Contracts for the International Sale of Goods does not apply to this Agreement. The laws of the jurisdiction where you are located may be different from California law.  You shall always comply with all international and domestic laws, ordinances, regulations, and statutes that are applicable to its purchase and use of the Website or Service hereunder.</p>
    <p><strong>8.3    Notices.</strong> If requested by Company, you shall be responsible for providing Company with your most current e-mail address.  In the event that the last e-mail address you provided to Company is not valid, or for any reason is not capable of delivering to you any notices required or permitted by this Agreement, Company’s dispatch of the e-mail containing such notice will nonetheless constitute effective notice.  You may give notice to Company at the following address: Computable LLC, 832 Sansome St First Floor, San Francisco, CA 94111. Such notice shall be deemed given when received by Company by letter delivered by nationally recognized overnight delivery service or first class postage prepaid mail at the above address.</p>
    <p><strong>8.4    Waiver.</strong>  Any waiver or failure to enforce any provision of this Agreement on one occasion will not be deemed a waiver of any other provision or of such provision on any other occasion.</p>
    <p><strong>8.5    Severability.</strong>  If any provision of this Agreement is, for any reason, held to be invalid or unenforceable, the other provisions of this Agreement will remain enforceable and the invalid or unenforceable provision will be deemed modified so that it is valid and enforceable to the maximum extent permitted by law.  Without limiting the generality of the foregoing, you agree that Section 6 (Limitation of Liability) will remain in effect notwithstanding the unenforceability of any provision in Section 5.1 (Limited Warranty).</p>
    <p><strong>8.6    Export Control.</strong>  You may not use, export, import, or transfer Website or Service except as authorized by U.S. law, the laws of the jurisdiction in which you obtained Website or Service, and any other applicable laws.  In particular, but without limitation, Website or Service may not be exported or re-exported (a) into any United States embargoed countries, or (b) to anyone on the U.S. Treasury Department’s list of Specially Designated Nationals or the U.S. Department of Commerce’s Denied Person’s List or Entity List. By using Website or Service, you represent and warrant that (i) you are not located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a “terrorist supporting” country and (ii) you are not listed on any U.S. Government list of prohibited or restricted parties. You agree that you will not use Website or Service for any purpose prohibited by U.S. law, including the development, design, manufacture or production of missiles, nuclear, chemical or biological weapons.  You acknowledge and agree that products, services or technology provided by Company are subject to the export control laws and regulations of the United States.  You agree to comply with these laws and regulations and shall not, without prior U.S. government authorization, export, re-export, or transfer Company products, services or technology, either directly or indirectly, to any country in violation of such laws and regulations.</p>
    <p><strong>8.7    Entire Agreement.</strong>  This Agreement is the final, complete and exclusive agreement of the parties with respect to the subject matter hereof and supersedes and merges all prior discussions between the parties with respect to such subject matter.</p>
    <p><strong>End of Agreement</strong></p>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator'

@Component
export default class Terms extends Vue {}
</script>
